---
apiVersion: v1
kind: Pod
metadata:
  name: activity
spec:
  initContainers:
    - name: alpine1
      image: alpine
      args:
        - sleep
        - 10s
    - name: alpine2
      image: alpine
      args:
        - sleep
        - 25s

  containers:
    - name: ngmaincar
      image: nginx:latest
      imagePullPolicy: IfNotPresent
      ports:
        - name: ngmaincarport
          containerPort: 8080
          protocol: TCP
      resources:
        requests:
          cpu: "125m"
          memory: "150Mi"
        limits:
          cpu: "250m"
          memory: "250Mi"
    - name: alpinesidecar
      image: alpine
      args:
        - sleep
        - 10s
      resources:
        requests:
          cpu: "125m"
          memory: "150Mi"
        limits:
          cpu: "250m"
          memory: "250Mi"
