---
apiVersion: v1
kind: Pod
metadata:
  name: nop-pod
  labels:
    app: nop
    env: dev
spec:
  containers:
    - name: nopcont
      image: shaikkhajaibrahim/nopcommercejune2024:070624
      ports:
        - name: nopport
          containerPort: 5000
          protocol: TCP
      resources:
        requests:
          cpu: "250m"
          memory: "64Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"
