---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: dev
spec:
  containers:
    - name: nginximg
      image: nginx:latest
      ports:
        - name: nginxport
          containerPort: 8080
          protocol: TCP
