---
apiVersion: v1
kind: StatefulSet
metadata:
  name: mysql-sts
spec:
  minReadySeconds: 10
  replicas: 2
  selector:
    matchLabels:
      app: spcmysql
  serviceName: mysql-svc
  template:
    metadata:
      name: mysqlpod
      labels:
        app: spcmysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysqcontainer
          image: mysql:latest
          ports:
            - name: mysqlport
              containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root123
            - name: MYSQL_DATABASE
              value: studentdb
            - name: MYSQL_USER
              value: admin
            - name: MYSQL_PASSWORD
              value: admin123          
          resources:
            limits:
              memory: 512Mi
              cpu: 1000m
          volumeMounts:
            - name: mysqlpvc
              mountPath: /var/lib/mysql

  volumeClaimTemplates:
    - metadata:
        name: mysqlpvc
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: managed-premium
          resources:
            requests:
              storage: 1Gi
