---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: nginx
spec:
  type: clusterIP
  clusterIP: None
  selector:
    app: spcmysql
  ports:
    - name: mysqlsvcport
      port: 3306
      targetPort: 3306
      protocol: TCP
