---
apiVersion: v1
kind: Pod
metadata:
  name: nginxpod
spec:
  nodeSelector:
    env: dev
  containers:
    - name: nginxcontainer
      image: nginx:latest
      ports:
        - name: ngwebport
          containerPort: 8080
          protocol: TCP
      resources:
        limits:
          cpu: "250m"
          memory: "128Mi"
