---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjobapp
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 10
      template:
        spec:
          containers:
            - name: hello
              image: alpine
              imagePullPolicy: IfNotPresent              
              command:
                - sleep
                - 90s
          restartPolicy: OnFailure
      parallelism: 2
