---
apiVersion: batch/v1
kind: Job
metadata:
  name: simple-job
spec:
  backoffLimit: 2
  template:
    metadata:
      name: simple-job
      labels:
        app: simple-jobapp
    spec:
      restartPolicy: OnFailure
      containers:
        - name: alpinecont
          image: alpine:latest
          args:
            - sleep
            - 5s
