---
apiVersion: app/v1
kind: ReplicaSet
metadata: 
  name: spc-rs
  labels:
    app: spcapp-rs
spec: 
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: spcapp
  template:
    metadata:
      name: spcapp-pod
      labels:
        app: spcapp
    spec:
      containers:
        - name: spccnt
          image: shaikkhajaibrahim/spcjan2024:1.0
          ports:
            - name: spcport
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "150m"
              memory: "150Mi"
            limits:
              cpu: "250m"
              memory: "250Mi"
