---
apiVersion: v1
kind: Service
metadata:
  name: frontapp-svc
spec:
  type: NodePort
  selector:
    app: frontapp
  ports:
    - name: frontapp-port
      targetPort: 80
      port: 80
      protocol: TCP
