---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spc-deployment
  annotations:
    kubernetes.io/change-cause: "First Version"
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: spcapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: spcapp-cont
      labels:
        app: spcapp
    spec:
      containers:
        - name: spccont
          image: panneercts/springpetclinic:v1.0
          ports:
            - name: spcport
              containerPort: 8080
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: spcapp-svc
spec:
  type: NodePort
  selector:
    app: spcapp
  ports:
    - name: spcapp-port
      targetPort: 8080
      port: 8080
      protocol: TCP
