---
apiVersion: v1
kind: Service
metadata:
  name: spcapp-svc
spec:
  type: NodePort
  selector:
    app: spcapp
  ports:
    - name: spcapp-port
      targetPort: 8080
      port: 8080
      protocol: TCP
