---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spc-deployment
  annotations:
    kubernetes.io/change-cause: "First Version"
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: spcapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: spcapp-cont
      labels:
        app: spcapp
    spec:
      containers:
        - name: sdsd
          image: shaikkhajaibrahim/dmtest:1.0
          ports:
            - name: spcport
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "250m"
              memory: "250Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
