---
apiVersion: v1
kind: Pod
metadata:
  name: filemod-pod
spec:
  containers:
    - name: filemodalpine-cont
      image: alpine:latest
      args:
        - sleep
        - 1d
    volumeMounts:
      - name: filemod-vol
        readOnly: true
        mountPath: /secretconfig
  volumes:
    - name: filemod-vol
      secret:
        secretName: mysql-sc
        optional: true
    