---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-mgmt
  template:
    metadata:
      labels:
        app: auth-mgmt
    spec:
      containers:
        - name: auth-mgmt
          image: digienvision/auth-mgmt:1.0
          ports:
            - name: auth-cnt-port
              containerPort: 8070
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_URL
              value: "mongodb://de:Digi123@mongo-service:27017/auth"
            - name: SPRING_DATASOURCE_USERNAME
              value: "de"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "Digi123"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-mgmt
  labels:
    app: auth-mgmt
spec:
  type: NodePort
  selector:
    app: auth-mgmt
  ports:
    - name: auth-svc-port
      port: 8070
      targetPort: 8070
      protocol: TCP
      nodePort: 30070
