---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx-cont
      image: nginx:latest
      ports:
        - name: nginx-port
          containerPort: 8080
          protocol: TCP