---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-mgmt
  template:
    metadata:
      labels:
        app: service-mgmt
    spec:
      containers:
        - name: service-mgmt
          image: digienvision/service-mgmt:1.5
          ports:
            - name: mgmt-cnt-port
              containerPort: 8090
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/de?useSSL=false&enabledTLSProtocols=TLSv1.2&allowPublicKeyRetrieval=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "Digi@123!!"
---
apiVersion: v1
kind: Service
metadata:
  name: service-mgmt
  labels:
    app: service-mgmt
spec:
  type: NodePort
  selector:
    app: service-mgmt
  ports:
    - name: mgmt-svc-port
      port: 8090
      targetPort: 8090
      protocol: TCP
      nodePort: 30090
