---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-service
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: mysql-spec
  serviceName: mysql-service
  template:
    metadata:
      name: mysql-spec
      labels:
        app: mysql-spec
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysqcontainer
          image: mysql:latest
          ports:
            - name: mysqlport
              containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Digi@123!!
            - name: MYSQL_DATABASE
              value: de
            - name: MYSQL_USER
              value: digienvision
            - name: MYSQL_PASSWORD
              value: Digi@123!!
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql-service
spec:
  clusterIP: None
  selector:
    app: mysql-spec
  ports:
    - name: mysql-spec-port
      port: 3306
      targetPort: 3306
      protocol: TCP