---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-deployment
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: invoiceapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: invoicepod
      labels:
        app: invoiceapp
      spec:
        containers:
          - name: invoicecont
            image: pitstop/invoiceservice:1.0
            imagePullPolicy: IfNotPresent
            restartPolicy: Always
            env:
              - name: DOTNET_ENVIRONMENT
                value: Production
