---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehiclemanagement-deployment
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: vehiclemanagementapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: vehiclemanagementpod
      labels:
        app: vehiclemanagementapp
      spec:
        containers:
          - name: vehiclemanagementcont
            image: pitstop/vehiclemanagementapi:1.0
            imagePullPolicy: IfNotPresent
            restartPolicy: Always
            env:
              - name: ASPNETCORE_ENVIRONMENT
                value: Production
            ports:
              - name: vehiclemanagementport
                containerPort: 5000
                protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: vehiclemanagement-svc
spec:
  type: NodePort
  selector:
    app: vehiclemanagementapp
  ports:
    - name: vehiclemanagementsvcport
      port: 5000
      targetPort: 5000
      protocol: TCP
