---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: webapppod
      labels:
        app: webapp
      spec:
        containers:
          - name: webappcont
            image: pitstop/webapp:1.0
            imagePullPolicy: IfNotPresent
            restartPolicy: Always
            env:
              - name: ASPNETCORE_ENVIRONMENT
                value: Production
            ports:
              - name: webappport
                containerPort: 7005
                protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - name: webappsvcport
      port: 7005
      targetPort: 7005
      protocol: TCP
