---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshopmngeventhandler-deployment
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: workshopmngeventhandlerapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: workshopmngeventhandlerpod
      labels:
        app: workshopmngeventhandlerapp
      spec:
        containers:
          - name: workshopmngeventhandlercont
            image: pitstop/workshopmanagementeventhandler:1.0
            imagePullPolicy: IfNotPresent
            restartPolicy: Always
            env:
              - name: DOTNET_ENVIRONMENT
                value: Production
