---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshopmanagement-deployment
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: workshopmanagementapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: workshopmanagementpod
      labels:
        app: workshopmanagementapp
      spec:
        containers:
          - name: workshopmanagementcont
            image: pitstop/workshopmanagementapi:1.0
            imagePullPolicy: IfNotPresent
            restartPolicy: Always
            env:
              - name: ASPNETCORE_ENVIRONMENT
                value: Production
            ports:
              - name: workshopmanagementport
                containerPort: 5200
                protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: workshopmanagement-svc
spec:
  type: NodePort
  selector:
    app: workshopmanagementapp
  ports:
    - name: workshopmanagementsvcport
      port: 5200
      targetPort: 5200
      protocol: TCP
