---
apiVersion: v1
kind: Namespace
metadata:
  name: dev

---
apiVersion: v1
kind: DaemonSet
metadata:
  name: logagent-deamon
  namespace: dev
spec:
  minReadySeconds: 5
  selector:
    matchLabels:
      app: logagent
  template:
    metadata:
      name: fluentdpod
      labels:
        app: logagent
    spec:
      containers:
        - name: fluentd
          image: fluentd:latest
          ports:
            - containerPort: 24224
              protocol: TCP
            - containerPort: 24224
              protocol: UDP
