---
apiVersion: v1
kind: Pod
metadata:
  name: filemount-pod
spec:
  containers:
    - name: filemodcont
      image: alpine:latest
      args:
        - sleep
        - 5d
      volumeMounts:
        - name: nop-cm-vol
          mountPath: /config
  volumes:
    - name: nop-cm-vol
      configMap: 
        name: nop-cm