---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysdqldb
    engine: mysql
spec:
  containers:
    - name: mysqcontainer
      image: mysql:latest
      ports:
        - name: mysqlport
          containerPort: 3306
          protocol: TCP
      envFrom:
        - configMapRef:
            name: nop-cm
      resources:
        limits:
          cpu: "250m"
          memory: "500Mi"
