---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginxreplica
spec:
  minReadySeconds: 3
  replicas: 5
  selector:
    matchLabels:
      app: nginxweb
  template:    
    metadata:
      name: nginxreplica-pod
      labels:
        app: nginxweb
        env: dev
    spec:
      containers:
        - name: nginxcontainer
          image: nginx:latest
          ports:
            - name: ngwebport
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: "250m"
              memory: "128Mi"
